title: Sean Koenig
logo: "/images/profile_image.png?raw=true"
description: >
  Data and coding portfolio
  <br><br>
  Connect on Twitter <a href="https://twitter.com/datacascadia">@datacascadia</a>
  <br><br>
  Or on <a href="https://www.linkedin.com/in/sean-koenig-seattle/">LinkedIn</a> profile

theme: jekyll-theme-minimal
